Remove the use of Mozilla's root certificates and certific.where()
influxdata/influxdb-client-python pull request #207
Opened 2021-03-15 14:54 UTC by borlaugen

Closes #206

## Proposed Changes

Remove the use of Mozilla's root certificates as default.

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `pytest tests` completes successfully
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [ ] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-03-15 15:19 UTC, bednar requested changes
Thanks for your PR 👍

Could you please update `CHANGELOG.md` file and fix following code style validation:

![image](https://user-images.githubusercontent.com/455137/111177080-3381a100-85aa-11eb-9747-bd0169956135.png)

2021-03-16 06:52 UTC, borlaugen commented
@bednar, I see that the test-3.6-influxdb-nightly task fails. Is this related to my pull request or something else?

Also, regarding the semantic pull request. Could you point me in the direction of how?

2021-03-16 06:58 UTC, bednar commented
@borlaugen, thanks again for you PR. 

The `test-3.6-influxdb-nightly` is our fault and It will be fixed after merge #209. The semantic PR requires that your commits messages and title of PR are in following format: https://www.conventionalcommits.org/en/v1.0.0/.

e.g: `feat: Remove the use of Mozilla's root certificates and certific.where()`, `docs: updated CHANGELOG.md`.

2021-03-16 07:01 UTC, borlaugen commented
@bednar, Thanks. Could we do the semantics through squasing at the end or do I have to update my commits?

2021-03-16 07:04 UTC, bednar commented
> Could we do the semantics through squasing at the end or do I have to update my commits?

Keep your commits as is and We will change titles in squashing.

2021-03-16 07:05 UTC, borlaugen commented
Thanks. Great product btw!

2021-03-16 08:01 UTC, bednar approved these changes

2021-03-16 08:16 UTC, merged