feat: optionally allow basic auth
influxdata/influxdb-client-python pull request #263
Opened 2021-05-26 14:05 UTC by reinhard-brandstaedter

feat: add option for basic auth when using influxdb 1.8 compatibility API

Closes #262

## Proposed Changes

Add an additional option ```auth_basic: True|False``` for the InfluxDBClient, which allows to use the client in cases where reverse proxies are being used for authentication instead of InfluxDBs own authentication (applies only for InfluxDB 1.8 forward compatibility API).
Using reverse proxies is quite a common setup, so this makes it easier to integrate in such scenarios.

## Checklist

- [ ] CHANGELOG.md updated
- [x] Rebased/mergeable
- [ ] A test has been added if appropriate
- [x] `pytest tests` completes successfully
- [x] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)
- [x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)

2021-05-27 07:02 UTC, bednar requested changes
Thanks for your PR 👍

There is a few requirements that should be satisfy before we accept the PR:

1. Please add documentation of `auth_basic` option to: https://github.com/influxdata/influxdb-client-python/blob/8c239580102bbc89aba00fc966a914b432f9f94b/influxdb_client/client/influxdb_client.py#L39
2. Add support for configuration by `config_file`:
https://github.com/influxdata/influxdb-client-python/blob/8c239580102bbc89aba00fc966a914b432f9f94b/influxdb_client/client/influxdb_client.py#L95
3. Add support for configuration by `env_properties`:
https://github.com/influxdata/influxdb-client-python/blob/8c239580102bbc89aba00fc966a914b432f9f94b/influxdb_client/client/influxdb_client.py#L183
4. Add new configuration option to `README.rst`: 
![image](https://user-images.githubusercontent.com/455137/119780080-ac19ad80-bec9-11eb-9aa6-d63629699a4d.png)
5. Add tests:
   - https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/tests/test_InfluxDBClient.py#L55
   - https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/tests/test_InfluxDBClient.py#L60

Regards

2021-05-27 07:46 UTC, reinhard-brandstaedter commented
Thanks @bednar will do!

I was just wondering, since this option would only apply when using the client in combination with the 1.8 compatibility API (AFAIK disabling auth for InfluxDB 2.0 is not an option?) if this configuration option should go into the [influx2] config section or if it makes sense to introduce a [influx1] compatibility section to make it more clear that this can/should only be used in combination with 1.8.
At the time of creating the influxdb_client one can only tell that the end-user is intending to connect to a InfluxDB 1.8 by looking at the ```org``` parameter and check if its value is "-". (would that be a correct assumption?).
So maybe I should also add a safety there to avoid that someone sets the ```auth_basic``` when intending to use it against InfluxDB 2.0.

kr

2021-05-27 07:56 UTC, bednar commented
> I was just wondering, since this option would only apply when using the client in combination with the 1.8 compatibility API (AFAIK disabling auth for InfluxDB 2.0 is not an option?) if this configuration option should go into the [influx2] config section or if it makes sense to introduce a [influx1] compatibility section to make it more clear that this can/should only be used in combination with 1.8.

Good point 👍 I think we can use `influx2` section with note that the option is suitable only for InfluxDB 1.8+.

> At the time of creating the influxdb_client one can only tell that the end-user is intending to connect to a InfluxDB 1.8 by looking at the `org` parameter and check if its value is "-". (would that be a correct assumption?).

I don't think so. It is too tricky.

> So maybe I should also add a safety there to avoid that someone sets the `auth_basic` when intending to use it against InfluxDB 2.0.

I think that a note in documentation that the option is suitable only for InfluxDB 1.8+ will be pretty enough.

2021-05-27 10:17 UTC, reinhard-brandstaedter commented
> > I was just wondering, since this option would only apply when using the client in combination with the 1.8 compatibility API (AFAIK disabling auth for InfluxDB 2.0 is not an option?) if this configuration option should go into the [influx2] config section or if it makes sense to introduce a [influx1] compatibility section to make it more clear that this can/should only be used in combination with 1.8.
> 
> Good point 👍 I think we can use `influx2` section with note that the option is suitable only for InfluxDB 1.8+.

Done

> > At the time of creating the influxdb_client one can only tell that the end-user is intending to connect to a InfluxDB 1.8 by looking at the `org` parameter and check if its value is "-". (would that be a correct assumption?).
> 
> I don't think so. It is too tricky.

I see, took a look and seems one can also use "-" as an org name in InfluxDB2. Indeed tricky. I'll leave it up to the user to read documentation and not use the option with 2.x

> > So maybe I should also add a safety there to avoid that someone sets the `auth_basic` when intending to use it against InfluxDB 2.0.
> 
> I think that a note in documentation that the option is suitable only for InfluxDB 1.8+ will be pretty enough.

Done

2021-05-27 13:24 UTC, bednar requested changes
@reinhard-brandstaedter, thanks again for your PR 👍

Please update `CHANGELOG.md` and we will be ready to merge PR into master.

2021-05-28 05:04 UTC, bednar approved these changes
LGTM 🥇

2021-05-28 05:14 UTC, merged