fix: parsing date fails due to thread race
influxdata/influxdb-client-python pull request #477
Opened 2022-07-29 19:27 UTC by rdinoff

Two python threads can call get_date_helper() simultaneously, causing a
partially-contstructed DateHelper object to be returned to the caller.

Closes #471 

## Proposed Changes

_Briefly describe your proposed changes:_
added lock

2022-08-01 05:46 UTC, bednar requested changes
@rdinoff thanks for your PR 👍. It is an awesome fix 💯 

Can you please satisfy our checklist before we accept this PR:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/455137/182078481-6c1225bc-c90a-4671-b751-42b95371023f.png">

and also there is a following requirement:

2022-08-01 05:46 UTC, bednar commented on influxdb_client/client/util/date_utils.py
> +                date_helper.parse_date = parser.parse
The acquiring locks is an expensive operation. We can use something like:

```suggestion
    if date_helper is None:
        with lock_:
            # avoid duplicate initialization
            if date_helper is None:
                _date_helper = DateHelper()
                try:
                    import ciso8601
                    _date_helper.parse_date = ciso8601.parse_datetime
                except ModuleNotFoundError:
                    _date_helper.parse_date = parser.parse
                date_helper = _date_helper
```

2022-08-05 16:50 UTC, powersj approved these changes
thanks for the PR!

2022-08-08 04:52 UTC, bednar approved these changes
@rdinoff thanks again for your PR 👍

2022-08-08 04:53 UTC, merged