feat: taks pagination
influxdata/influxdb-client-python pull request #616
Opened 2023-11-21 14:04 UTC by Sciator

Closes #614

## Proposed Changes

added `tasks_api.find_tasks_iter`

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `pytest tests` completes successfully
- [ ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2023-11-21 14:12 UTC, Sciator commented
Currently creates one more request than needed. Better identification of last page needed

2023-11-23 14:13 UTC, bednar requested changes
Thank you for your PR! 👍 Before we can accept it, there are a few requirements that need to be met:

2023-11-23 14:13 UTC, bednar commented on influxdb_client/client/tasks_api.py
> +        return tasks, next
This is private function, please move it at bottom of the file.

2023-11-23 14:13 UTC, bednar commented on influxdb_client/client/tasks_api.py
> +        def next():
The `next` is build-in Python name, please rename to something like: `next_`.

2023-11-23 14:13 UTC, bednar commented on influxdb_client/client/tasks_api.py
> +        tasks, next = self._find_tasks_paged(**kwargs)
The `next` is build-in Python name, please rename to something like: `next_`.

2023-11-23 14:13 UTC, bednar commented on influxdb_client/client/tasks_api.py
> +        self.next = next
The `next` is build-in Python name, please rename to something like: `next_`.

2023-11-23 14:13 UTC, bednar commented on influxdb_client/client/tasks_api.py
> +        return self.values.pop(0)
Please refactor the iterator to a generic format. We should be able to reuse `_TasksIterator` (as `_NextIterator`) in other APIs, such as `organizations_api`.

2023-11-29 11:21 UTC, bednar approved these changes
LGTM :rocket:

2023-11-29 11:22 UTC, merged