silence pandas 3.0 warning
influxdata/influxdb-client-python pull request #642
Opened 2024-02-02 16:49 UTC by lars20070

Closes #

## Proposed Changes

Currently, the Pandas 3.0 warning is triggered.

```
~/.venv/lib/python3.11/site-packages/influxdb_client/client/write/dataframe_serializer.py:237: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
```

The pull request silences the warning.

## Checklist

- [ x] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] `pytest tests` completes successfully
- [ ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2024-02-05 06:30 UTC, bednar requested changes
Hi @lars20070, first off, thank you for your contribution through the PR, it's greatly appreciated! 👍 

Could you please explain why Pandas recommends using the syntax: `For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)'`? 

It seems our sources employ this recommended syntax.

Best Regards

2024-02-05 08:33 UTC, lars20070 commented
Hi @bednar, Pandas is currently in version 2.2 with [3.0 scheduled for April 2024](https://towardsdatascience.com/deep-dive-into-pandas-copy-on-write-mode-part-iii-c024eaa16ed4). No, I cannot explain why Pandas triggered the warning. But you might be on the safe side using option 2 and be prepared for the upcoming breaking changes. I can see your #638 changes but still get the warning from this line.

2024-02-05 08:39 UTC, bednar requested changes
Hi @lars20070,

Thank you for your thorough explanation and for aligning your solution with best practices recommended by Pandas. 

Before we proceed to merge your PR, could you please ensure that all items on our project's Checklist are satisfied? 

![image](https://github.com/influxdata/influxdb-client-python/assets/455137/030bfce5-138d-4e0a-9a40-9b7c72e140da)

After that we are be able to merge this PR.

Thanks again for your contribution 👍

2024-02-05 09:00 UTC, lars20070 commented
@bednar I struggle a bit to understand your setup. I am more familiar with Poetry projects. I would appreciate your input.

- [x]  I have updated the `CHANGELOG.md`.
- [ ]  I forked yesterday. So no need to rebase. I see no merge conflicts.
- [ ]  `pytest` seems to not be running in your CI. I see no failing tests.
- [ ] Guess my commit message was not quite conventional.

 Can you please explain what changes in the code are needed. Thanks.

2024-02-05 09:42 UTC, bednar commented
@lars20070, please sign the CLA and check the checkbox so we can proceed with merging your PR.

2024-02-05 09:47 UTC, lars20070 commented
Signed. Thanks @bednar.

2024-02-05 10:16 UTC, bednar approved these changes
LGTM 🚀

2024-02-05 10:24 UTC, lars20070 commented
On a totally unrelated note. Any chance of looking into [this issue](https://github.com/influxdata/vsflux/issues/445)?
Apologies for cross-posting.

2024-02-06 06:48 UTC, bednar commented
@lars20070 unfurnetally I don't know anything about `vsflux`... I am at JetBrains IDEs ;)

2024-02-06 06:49 UTC, merged